### ISSUE TITLE
Discovering token fails to match audience on RHEL7

### ISSUE THREAD

**Issue by duncanmmacleod** [scitokens/scitokens#133]
`SciToken.discover(audience='ANY')` fails to return a valid token when executed on RHEL 7 (SL7), presumably due to some incompatibility with PyJWT:

```console
$ rpm -qa python36-jwt python36-scitokens htgettoken
python36-jwt-1.6.4-2.el7.noarch
htgettoken-1.7-2.osg35.el7.x86_64
python36-scitokens-1.6.2-2.osg35.el7.noarch
$ htgettoken -a fermicloud543.fnal.gov -i ligo
Attempting to get token from https://fermicloud543.fnal.gov:8200 ... succeeded
Storing bearer token in /run/user/42171/bt_u42171
$ /usr/bin/python3 -c "from scitokens import SciToken; token = SciToken.discover(audience='ANY'); print(list(token.claims()))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/scitokens/scitokens.py", line 348, in discover
    audience, require_key, insecure, public_key)
  File "/usr/lib/python3.6/site-packages/scitokens/scitokens.py", line 290, in deserialize
    options={"verify_signature": False})
  File "/usr/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/usr/lib/python3.6/site-packages/jwt/api_jwt.py", line 141, in _validate_claims
    self._validate_aud(payload, audience)
  File "/usr/lib/python3.6/site-packages/jwt/api_jwt.py", line 190, in _validate_aud
    raise InvalidAudienceError('Invalid audience')
jwt.exceptions.InvalidAudienceError: Invalid audience
```

However, if I upgrade my stack using conda, I get a working discover:

```console
$ conda list -n scitokens
# packages in environment at /home/duncan.macleod/.conda/envs/scitokens:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
cryptography              3.4.8            py39h95dcef6_1    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
ipython                   7.29.0           py39hef51801_2    conda-forge
jedi                      0.18.1           py39hf3d152e_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5           py39hde42818_1002    conda-forge
prompt-toolkit            3.0.22             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_0    conda-forge
python                    3.9.7           hb7a2778_3_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
scitokens                 1.6.2              pyhd8ed1ab_0    conda-forge
setuptools                59.2.0           py39hf3d152e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h9cd32fc_2    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
$ ~/.conda/envs/scitokens/bin/python3 -c "from scitokens import SciToken; token = SciToken.discover(audience='ANY'); print(list(token.claims()))"
[('sub', 'http://cilogon.org/serverA/users/7136'), ('aud', ['ANY', 'LIGO', 'segments.ligo.org']), ('ver', 'scitoken:2.0'), ('nbf', 1637740455), ('scope', 'write:/DQSegDB read:/frames read:/DQSegDB'), ('iss', 'https://cilogon.org/ligo'), ('exp', 1637762060), ('iat', 1637740460), ('jti', 'https://cilogon.org/oauth2/7587a2c78324a6bf35031f4b2c1b8d09?type=accessToken&ts=1637740459700&version=v2.0&lifetime=21600000'), ('cid', 'cilogon:/client_id/48e4b943658c2b1d70057d8d5d21c21e')]
```

**Comment by duncanmmacleod** [comment]
A simpler reproducer of a working environment for those who don't use conda is as follows, from the same SL7 starting point as above:

```console
$ python3 -m venv --system-site-packages venv
$ ./venv/bin/python3 -m pip install -U pip --quiet
$ ./venv/bin/python3 -m pip install pyjwt[crypto]==2.0.0 cryptography==3.3.1
Collecting pyjwt[crypto]==2.0.0
  Using cached PyJWT-2.0.0-py3-none-any.whl (15 kB)
Collecting cryptography==3.3.1
  Downloading cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 25.6 MB/s
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (405 kB)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.6/site-packages (from cryptography==3.3.1) (1.14.0)
Requirement already satisfied: pycparser in /usr/lib/python3.6/site-packages (from cffi>=1.12->cryptography==3.3.1) (2.14)
/home/duncan.macleod/venv/lib64/python3.6/site-packages/pip/_vendor/packaging/specifiers.py:276: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
Installing collected packages: cffi, pyjwt, cryptography
  Attempting uninstall: cffi
    Found existing installation: cffi 1.9.1
    Not uninstalling cffi at /usr/lib64/python3.6/site-packages, outside environment /home/duncan.macleod/venv
    Can't uninstall 'cffi'. No files were found to uninstall.
  Attempting uninstall: pyjwt
    Found existing installation: PyJWT 1.6.4
    Not uninstalling pyjwt at /usr/lib/python3.6/site-packages, outside environment /home/duncan.macleod/venv
    Can't uninstall 'PyJWT'. No files were found to uninstall.
  Attempting uninstall: cryptography
    Found existing installation: cryptography 2.3
    Not uninstalling cryptography at /usr/lib64/python3.6/site-packages, outside environment /home/duncan.macleod/venv
    Can't uninstall 'cryptography'. No files were found to uninstall.
Successfully installed cffi-1.15.0 cryptography-3.3.1 pyjwt-2.0.0
$ venv/bin/python3 -c "from scitokens import SciToken; token = SciToken.discover(audience='ANY'); print(list(token.claims()))"
[('sub', 'http://cilogon.org/serverA/users/7136'), ('aud', ['ANY', 'LIGO', 'segments.ligo.org']), ('ver', 'scitoken:2.0'), ('nbf', 1637740455), ('scope', 'write:/DQSegDB read:/frames read:/DQSegDB'), ('iss', 'https://cilogon.org/ligo'), ('exp', 1637762060), ('iat', 1637740460), ('jti', 'https://cilogon.org/oauth2/7587a2c78324a6bf35031f4b2c1b8d09?type=accessToken&ts=1637740459700&version=v2.0&lifetime=21600000'), ('cid', 'cilogon:/client_id/48e4b943658c2b1d70057d8d5d21c21e')]
```

I haven't tested exhaustively, but am pretty sure pyjwt-2.0.0 is the oldest version that works, the same `venv` with pyjwt-1.7.1 still fails with `Invalid Audience`.
