### ISSUE TITLE
validate() throws error when parsing WLCG token parsing

### ISSUE THREAD

**Issue by jteheran** [scitokens/scitokens#88]
```
>>> val.validate(token)
Traceback (most recent call last):  
    File "<stdin>", line 1, in <module>  
    File "/usr/lib/python2.7/site-packages/scitokens/scitokens.py", line 369, in validate    
for claim, value in token.claims():AttributeError: 'str' object has no attribute 'claims'
```

**Comment by djw8605** [comment]
It almost sounds like you are passing the raw token text to the validate function rather than the token object.  Can you give a bit of example code to show the issue in contect?

**Comment by jteheran** [comment]
Yes, I am passing the raw token text. I am trying to use deserialize() to create the token object, but it is failing (as shown in the issue #89 )

I tested validate() with a scitoken from the web app:

```
>>> token4 = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImtleS1yczI1NiJ9.eyJpc3MiOiJodHRwczovL2RlbW8uc2NpdG9rZW5zLm9yZyIsImV4cCI6MTU5MDA4MjYwNywiaWF0IjoxNTkwMDgyMDA3LCJuYmYiOjE1OTAwODIwMDcsImp0aSI6ImI3ZGNiYTAzLTQwNTItNGQwMS04MTBkLWI3MWFkNWVlYmVhZiJ9.kz4zlJZHCwQCQ3ZP_VoE6YS_tf9tkLG2lpvA5j-hT6VowoRNw3sgDsKAAmhkz0Cjw6JmavqnfwcP3xx7l7jNEsYifMS-RthH5dQh9phUHwxtmwCVq1-udAg-K78NIl_vRkUTDB1tjDqGqqNTJ5iRXyjUknlYlPt7GHcBAYV6V7jXuRWxUV9pMIuV-Z7DvfRa0yzP-r9hfTCRF8xMXzkW43VaHwOetQJaW_nRoPUKleRKp0wurbOLrkurRDeZq2Q3cqDnVjHOTmHC76kAeav2uxfXnZZ3D1M805hoRahCXtA7J9Y_J3Wi1YOr92RRzK5zPCOA73ka-nSsAp9M7vM4Rg"
>>> stoken4 = scitokens.SciToken.deserialize(token4)
>>> val.validate(stoken4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/scitokens/scitokens.py", line 374, in validate
    raise NoRegisteredValidator("No validator was registered to handle encountered claim '%s'" % claim)
scitokens.scitokens.NoRegisteredValidator: No validator was registered to handle encountered claim 'iss'
```
I believe this behavior is expected.

**Comment by djw8605** [comment]
Yes, I think this is an extension of #89.  Lets solve that issue.
