### ISSUE TITLE
deserialize() says invalid audience when parsing WLCG token

### ISSUE THREAD

**Issue by jteheran** [scitokens/scitokens#89]
```
>>> stoken = scitokens.SciToken.deserialize(token)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/scitokens/scitokens.py", line 281, in deserialize
    claims = jwt.decode(serialized_token, issuer_public_key)
  File "/usr/lib/python2.7/site-packages/jwt/api_jwt.py", line 104, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/usr/lib/python2.7/site-packages/jwt/api_jwt.py", line 140, in _validate_claims
    self._validate_aud(payload, audience)
  File "/usr/lib/python2.7/site-packages/jwt/api_jwt.py", line 189, in _validate_aud
    raise InvalidAudienceError('Invalid audience')
jwt.exceptions.InvalidAudienceError: Invalid audience
```

**Comment by djw8605** [comment]
Do you have an example of a token that causes this issue?

**Comment by jteheran** [comment]
```
>>> wlcgtokenraw = "eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJ3bGNnLnZlciI6IjEuMCIsInN1YiI6Ijg5N2VjOTI4LWQ5MTAtNDY2NC05YjE1LTgyOTZkMWZlZjg2MyIsImF1ZCI6Imh0dHBzOlwvXC93bGNnLmNlcm4uY2hcL2p3dFwvdjFcL2FueSIsIm5iZiI6MTU5MDA3OTYyOCwic2NvcGUiOiJhZGRyZXNzIG9wZW5pZCBwcm9maWxlIHN0b3JhZ2UucmVhZDpcLyBlZHVwZXJzb25fZW50aXRsZW1lbnQgd2xjZyBzdG9yYWdlLmNyZWF0ZTpcLyBwaG9uZSBvZmZsaW5lX2FjY2VzcyBlZHVwZXJzb25fc2NvcGVkX2FmZmlsaWF0aW9uIHN0b3JhZ2UubW9kaWZ5OlwvIGVtYWlsIHdsY2cuZ3JvdXBzIiwiaXNzIjoiaHR0cHM6XC9cL3dsY2cuY2xvdWQuY25hZi5pbmZuLml0XC8iLCJleHAiOjE1OTAwODMyMjgsImlhdCI6MTU5MDA3OTYyOCwianRpIjoiMmU0ZmI0M2YtMTNkZS00YTA5LWIzOGMtMWNjMjRlYzlmNzVhIiwiY2xpZW50X2lkIjoiN2M0YmYxOGEtNmU5NC00MzAxLTg1Y2UtMjAyMDJmNGQzNjIxIiwid2xjZy5ncm91cHMiOlsiXC93bGNnIiwiXC93bGNnXC9waWxvdHMiLCJcL3dsY2dcL3hmZXJzIl19.CVpfTRXV33M0VzTKcM2yuwE4YWJttPEG6SIVrhbf3UtckAh6jW5_B6rMUNar_hBNCjWsNipmmx3dFwLh0dq_96ZIDgNeSySVr4Gxanxd-RtDJ_YT0A5Hm16_IYyGmRkYgUUOYwep0g05_cdYOsCXb-jQf7Y9krQ8RQp_BhPwCtg"
>>> stokenwlcg = scitokens.SciToken.deserialize(wlcgtokenraw)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/scitokens/scitokens.py", line 281, in deserialize
    claims = jwt.decode(serialized_token, issuer_public_key)
  File "/usr/lib/python2.7/site-packages/jwt/api_jwt.py", line 104, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/usr/lib/python2.7/site-packages/jwt/api_jwt.py", line 140, in _validate_claims
    self._validate_aud(payload, audience)
  File "/usr/lib/python2.7/site-packages/jwt/api_jwt.py", line 189, in _validate_aud
    raise InvalidAudienceError('Invalid audience')
jwt.exceptions.InvalidAudienceError: Invalid audience
```

**Comment by djw8605** [comment]
Part of the deserialization is checking a few attributes for correctness.  One of those attributes is the `aud` (audience) claim.  The audience is expected to be specified in the deserialize function.  The API docs show how to specify it: https://scitokens.org/scitokens/scitokens.html#scitokens.scitokens.SciToken.deserialize

For the token you showed above, the audience will need to exactly match the aud in the token, which is: `https://wlcg.cern.ch/jwt/v1/any`

**Comment by jteheran** [comment]
I added the audience field and deserialize() succeeded.
However, I am seeing an error when I try to validate the token:

```
>>> val.validate(stokenwlcg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/scitokens/scitokens.py", line 374, in validate
    raise NoRegisteredValidator("No validator was registered to handle encountered claim '%s'" % claim)
scitokens.scitokens.NoRegisteredValidator: No validator was registered to handle encountered claim 'sub'
```
I may have missed an important step in the docs.

**Comment by djw8605** [comment]
Ah, the validation is a bit of "low" level.  The calling program has to perform a lot of steps to add validation.  I would look into the Enforcer:
https://scitokens.org/scitokens/#enforcing-scitokens-logic

The Enforcer is much higher level.  It defines a ton of standard "validators" with reasonable defaults.  It's meant for querying a token for "read" or "write" access to resources.

**Comment by jteheran** [comment]
Tried Enforcer. generate_acls and test:
```
>>> wtoken = "eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyN..."
>>> aud = "https://wlcg.cern.ch/jwt/v1/any"
>>> issuer = "https://wlcg.cloud.cnaf.infn.it/"
>>> stokenw = scitokens.SciToken.deserialize(wtoken, audience=aud)
>>> enf = scitokens.Enforcer(issuer, audience=aud)
>>> enf.generate_acls(stokenw)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/scitokens/scitokens.py", line 508, in generate_acls
    self._validator.validate(token, critical_claims=critical_claims)
  File "/usr/lib/python2.7/site-packages/scitokens/scitokens.py", line 374, in validate
    raise NoRegisteredValidator("No validator was registered to handle encountered claim '%s'" % claim)
scitokens.scitokens.NoRegisteredValidator: No validator was registered to handle encountered claim 'wlcg.groups'
```

**Comment by djw8605** [comment]
Ah, yes.  wlcg.groups is not a recognized SciToken schema for v1.  In the SciTokens 2.0 spec, it is supposed to ignore unknown claims in the token, but the python library was never updated to 2.0 spec.  Though, it should at some point.  The C++ library though does understand the 2.0 spec.

**Comment by jteheran** [comment]
I was able to deserialize a WLCG token with the C++ library. I also tested scitokens-list-access and the ACLs were displayed correctly.

This issue can be closed.
